// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: MonitoringUI

#ifndef _MONITORINGUI_UI_H
#define _MONITORINGUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_headerNotification;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_headerDate;
extern lv_obj_t * ui_headerTime;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_SolarPage;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Side2;
extern lv_obj_t * ui_widgetParamater3;
extern lv_obj_t * ui_basePanel3;
extern lv_obj_t * ui_solarVoltage;
extern lv_obj_t * ui_labelUnit3;
extern lv_obj_t * ui_labelTitle3;
extern lv_obj_t * ui_widgetParamater4;
extern lv_obj_t * ui_basePanel4;
extern lv_obj_t * ui_solarCurrent;
extern lv_obj_t * ui_labelUnit4;
extern lv_obj_t * ui_labelTitle4;
extern lv_obj_t * ui_widgetParamater5;
extern lv_obj_t * ui_basePanel5;
extern lv_obj_t * ui_solarPower;
extern lv_obj_t * ui_labelUnit5;
extern lv_obj_t * ui_labelTitle5;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_chartSolarVC;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_chartSolarPower;
extern lv_obj_t * ui_WindPage;
extern lv_obj_t * ui_Container25;
extern lv_obj_t * ui_Side3;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Container23;
extern lv_obj_t * ui_speedWind;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Side8;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Container24;
extern lv_obj_t * ui_degreesWind;
extern lv_obj_t * ui_directionWind;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Side1;
extern lv_obj_t * ui_widgetParamater;
extern lv_obj_t * ui_basePanel;
extern lv_obj_t * ui_windVoltage;
extern lv_obj_t * ui_labelUnit;
extern lv_obj_t * ui_labelTitle;
extern lv_obj_t * ui_widgetParamater1;
extern lv_obj_t * ui_basePanel1;
extern lv_obj_t * ui_windCurrent;
extern lv_obj_t * ui_labelUnit1;
extern lv_obj_t * ui_labelTitle1;
extern lv_obj_t * ui_widgetParamater2;
extern lv_obj_t * ui_basePanel2;
extern lv_obj_t * ui_windPower;
extern lv_obj_t * ui_labelUnit2;
extern lv_obj_t * ui_labelTitle2;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_chartWindVC;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_chartWindPower;
extern lv_obj_t * ui_SolarWindPage;
extern lv_obj_t * ui_Container29;
extern lv_obj_t * ui_Side5;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Container26;
extern lv_obj_t * ui_speedSolarWind;
extern lv_obj_t * ui_Label59;
extern lv_obj_t * ui_Side9;
extern lv_obj_t * ui_Label60;
extern lv_obj_t * ui_Container27;
extern lv_obj_t * ui_degreesSolarWind;
extern lv_obj_t * ui_directionSolarWind;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Side4;
extern lv_obj_t * ui_widgetParamater7;
extern lv_obj_t * ui_basePanel10;
extern lv_obj_t * ui_solarWindVoltage;
extern lv_obj_t * ui_labelUnit9;
extern lv_obj_t * ui_labelTitle7;
extern lv_obj_t * ui_widgetParamater9;
extern lv_obj_t * ui_basePanel11;
extern lv_obj_t * ui_solarWindCurrent;
extern lv_obj_t * ui_labelUnit10;
extern lv_obj_t * ui_labelTitle9;
extern lv_obj_t * ui_widgetParamater10;
extern lv_obj_t * ui_basePanel12;
extern lv_obj_t * ui_solarWindPower;
extern lv_obj_t * ui_labelUnit11;
extern lv_obj_t * ui_labelTitle10;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_chartSolarWindVC;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_chartSolarWindPower;
extern lv_obj_t * ui_BatteryPage;
extern lv_obj_t * ui_Container22;
extern lv_obj_t * ui_batteryBar;
extern lv_obj_t * ui_batteryPercent;
extern lv_obj_t * ui_percentIcon;
extern lv_obj_t * ui_Container21;
extern lv_obj_t * ui_chartBattery;
extern lv_obj_t * ui_ConsumptionPage;
extern lv_obj_t * ui_Side7;
extern lv_obj_t * ui_widgetParamater14;
extern lv_obj_t * ui_basePanel18;
extern lv_obj_t * ui_facilitiesPower;
extern lv_obj_t * ui_labelUnit18;
extern lv_obj_t * ui_labelTitle14;
extern lv_obj_t * ui_widgetParamater13;
extern lv_obj_t * ui_statusPanel;
extern lv_obj_t * ui_facilitiesStatus;
extern lv_obj_t * ui_labelTitle13;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_chartPower;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_legendsContainer1;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_legends1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Container30;
extern lv_obj_t * ui_brgyPower1;
extern lv_obj_t * ui_unit1;
extern lv_obj_t * ui_legends5;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Container28;
extern lv_obj_t * ui_healthPower1;
extern lv_obj_t * ui_unit;
extern lv_obj_t * ui_legends2;
extern lv_obj_t * ui_label2;
extern lv_obj_t * ui_Container31;
extern lv_obj_t * ui_daycarePower1;
extern lv_obj_t * ui_unit2;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_chartFacilities;
extern lv_obj_t * ui_TabView2;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_Container16;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Container19;
extern lv_obj_t * ui_brgyPower;
extern lv_obj_t * ui_brgyFreq;
extern lv_obj_t * ui_brgyFactor;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Container17;
extern lv_obj_t * ui_healthPower;
extern lv_obj_t * ui_healthFreq;
extern lv_obj_t * ui_healthFactor;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_Container18;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_Container20;
extern lv_obj_t * ui_daycarePower;
extern lv_obj_t * ui_daycareFreq;
extern lv_obj_t * ui_daycareFactor;
extern lv_obj_t * ui_SensorPage;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_statusSolarCurrent;
extern lv_obj_t * ui_statusWindCurrent;
extern lv_obj_t * ui_statusSolarVoltage;
extern lv_obj_t * ui_statusWindVoltage;
extern lv_obj_t * ui_statusBattVoltage;
extern lv_obj_t * ui_statusAnemo;
extern lv_obj_t * ui_statusPzemA;
extern lv_obj_t * ui_statusPzemB;
extern lv_obj_t * ui_statusPzemC;
extern lv_obj_t * ui_statusSim;
extern lv_obj_t * ui_statusWifi;
extern lv_obj_t * ui_statusCard;
extern lv_obj_t * ui____initial_actions0;





LV_FONT_DECLARE(ui_font_Roboto_Bold_10);
LV_FONT_DECLARE(ui_font_Roboto_Bold_12);
LV_FONT_DECLARE(ui_font_Roboto_Bold_16);
LV_FONT_DECLARE(ui_font_Roboto_Bold_20);
LV_FONT_DECLARE(ui_font_Roboto_Bold_24);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
